services:
  - type: web
    name: springboot-docker-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: "/actuator/health"  # Kiểm tra sức khỏe ứng dụng nếu có actuator
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod